apiVersion: v1
kind: Pod
metadata:
  name: subscribeandstore
spec:
  restartPolicy: Never
  containers:
  - name: subscribeandstore
    image: python/subscribeandstore
    imagePullPolicy: Never
    volumeMounts:
    - mountPath: "/db"
      name: db-pv-claim-0

  volumes:
  - name: db-pv-claim-0
    persistentVolumeClaim:
      claimName: db-pv-claim

